# Generated by Django 4.1.7 on 2023-02-25 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeApp', '0003_add_slug_to_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip',
            field=models.BigIntegerField(default=5100),
            preserve_default=False,
        ),
    ]
